/**
 * This file generated by Apso.
 */ /* eslint @typescript-eslint/no-unused-vars: "off" */

import {
  Column,
  Entity,
  PrimaryGeneratedColumn,
  Generated,
  JoinColumn,
  JoinTable,
  Index,
  Unique,
  PrimaryColumn,
} from 'typeorm';
import {
  IsOptional,
  IsString,
  MaxLength,
  IsNotEmpty,
  IsEmail,
  IsBoolean,
  ValidateNested,
} from 'class-validator';
import { Type } from 'class-transformer';
import { CrudValidationGroups } from '@nestjsx/crud';

const { CREATE, UPDATE } = CrudValidationGroups;

@Entity('analytics')
@Index(['survey_id', 'question_id', 'response_id'])
export class Analytics {
  // Fields
  @PrimaryGeneratedColumn()
  id!: number;

  @Column({ type: 'bigint' })
  survey_id: string;

  @Column({ type: 'bigint' })
  question_id: string;

  @Column({ type: 'bigint' })
  response_id: string;

  // Associations
}
