import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class ResponseCreate {
  @ApiProperty()
  value: string;
  @ApiProperty()
  question_id: string;
}

export class Response {
  @ApiProperty()
  id: number;
  @ApiProperty()
  value: string;
  @ApiProperty()
  question_id: string;
}
