import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class SurveyCreate {
  @ApiProperty()
  name: string;
  @ApiProperty()
  description: string;
  @ApiProperty()
  is_active: boolean;
  @ApiProperty()
  created_by: string;
  @ApiProperty()
  created_at: Date;
  @ApiProperty()
  updated_by: string;
  @ApiProperty()
  updated_at: Date;
}

export class Survey {
  @ApiProperty()
  id: number;
  @ApiProperty()
  name: string;
  @ApiProperty()
  description: string;
  @ApiProperty()
  is_active: boolean;
  @ApiProperty()
  created_by: string;
  @ApiProperty()
  created_at: Date;
  @ApiProperty()
  updated_by: string;
  @ApiProperty()
  updated_at: Date;
}
